_resolved:
    value:
        bucket_key: 128px_ar1:1
        data_root: /datasets/lindell-proj/neumayr/nersemble_v2/processed/128-res
        load_from_128_for_64_high_t: false
        train_target_frames: 9
        train_target_hw:
            - 128
            - 128
_wandb:
    value:
        cli_version: 0.24.0
        e:
            halkmgxwrosu7u0xaca47yyba12yid91:
                args:
                    - /home/piado/projects/aip-lindell/piado/vae/Open-Sora/configs/vae/train/wan_multiview_finetune.py
                    - --model.fusion_mode
                    - cross_attention
                    - --model.lora_rank
                    - "128"
                    - --experiment_name
                    - cross_attention_rank128
                cpu_count: 64
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "33501757440"
                        used: "8683409408"
                email: pia.donabauer@campus.lmu.de
                executable: /cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.5/bin/python
                git:
                    commit: 0ada0c67bbde440f15fc917805d420251d5aae97
                    remote: git@github.com:piadonabauer/vae.git
                gpu: NVIDIA L40S
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "48305799168"
                      name: NVIDIA L40S
                      uuid: GPU-3e41795a-a0a9-e620-6079-4faff8371ab1
                host: kn044
                memory:
                    total: "540453662720"
                os: Linux-6.8.0-54-generic-x86_64-Intel-R-_Xeon-R-_Gold_6338_CPU_@_2.00GHz-with-glibc2.37
                program: /home/piado/projects/aip-lindell/piado/vae/Open-Sora/scripts/vae/train.py
                python: CPython 3.11.5
                root: outputs/cross_attention_rank128
                slurm:
                    array_job_id: "2546589"
                    array_task_count: "8"
                    array_task_id: "2"
                    array_task_max: "8"
                    array_task_min: "1"
                    array_task_step: "1"
                    cluster_name: killarney
                    cpus_on_node: "8"
                    cpus_per_task: "8"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: aip-lindell
                    job_cpus_per_node: "8"
                    job_end_time: "1774409886"
                    job_gid: "3156567"
                    job_gpus: "0"
                    job_id: "2546645"
                    job_name: vae_sweep
                    job_nodelist: kn044
                    job_num_nodes: "1"
                    job_partition: gpubase_l40s_b2
                    job_qos: normal
                    job_start_time: "1774388286"
                    job_uid: "3156567"
                    job_user: piado
                    jobid: "2546645"
                    localid: "0"
                    mem_per_node: "65536"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: kn044
                    prio_process: "0"
                    procid: "0"
                    script_context: prolog_task
                    submit_dir: /project/6101839/piado
                    submit_host: klogin03
                    task_pid: "57866"
                    tasks_per_node: "1"
                    tmpdir: /tmp
                    topology_addr: ib-core1.ib-leaf1.kn044
                    topology_addr_pattern: switch.switch.node
                    tres_per_task: cpu=8
                startedAt: "2026-03-24T21:39:16.328179Z"
                writerId: halkmgxwrosu7u0xaca47yyba12yid91
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 70
                - 71
                - 82
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 70
                - 71
                - 82
                - 98
            "3":
                - 3
                - 13
                - 16
                - 61
            "4": 3.11.5
            "5": 0.24.0
            "6": 4.51.3
            "12": 0.24.0
            "13": linux-x86_64
DATA_ROOT:
    value: /datasets/lindell-proj/neumayr/nersemble_v2/processed/128-res
all_people_expression_sequence:
    value: EMO-1-shout+laugh
batch_size:
    value: 1
bucket_config:
    value:
        128px_ar1:1:
            "9":
                - 1
                - 1
ckpt_every:
    value: 500
config_path:
    value: /home/piado/projects/aip-lindell/piado/vae/Open-Sora/configs/vae/train/wan_multiview_finetune.py
data_preset:
    value: single_sequence
dataset:
    value:
        data_path: /datasets/lindell-proj/neumayr/nersemble_v2/processed/128-res/p018/EMO-1-shout+laugh/EMO-1-shout+laugh.pt
        repeat: 1
        type: pt_video
dtype:
    value: bf16
ema_decay:
    value: 0.9999
epochs:
    value: 10000
eval_batch_size:
    value: 1
eval_every:
    value: 200
eval_num_samples:
    value: 3
eval_use_ema:
    value: true
experiment_folder:
    value: /project/6101839/piado/vae/Open-Sora/outputs/cross_attention_rank128
experiment_name:
    value: cross_attention_rank128
final_eval:
    value: true
final_eval_num_samples:
    value: 3
fixed_seq_eval_every_epochs:
    value: 200
full_eval_every:
    value: 1000
grad_checkpoint:
    value: false
grad_clip:
    value: 1
keep_n_latest:
    value: 3
log_bottleneck_every:
    value: 200
log_every:
    value: 100
log_latent_shapes_every:
    value: 500
log_memory:
    value: false
log_step_time:
    value: true
lr_scheduler:
    value:
        warmup_steps: 0
mixed_image_ratio:
    value: 0
mixed_strategy:
    value: null
model:
    value:
        freeze_temporal: true
        from_pretrained: /home/piado/scratch/Wan2.1_VAE.pth
        from_scratch: false
        fusion_mode: cross_attention
        lora_rank: 128
        train_spatial: true
        type: multiview_wan_video_vae
        use_crossview_encoder: true
        use_lora: true
        use_lora_after: true
        use_lora_before: false
        use_view_embedding: false
        use_view_group_fusion: false
        use_viewwise_decoder_lora: false
        view_compression: 2
        view_in: 2
        view_mixing_strategy: embedding
        z_dim: 16
nersemble_processed_base:
    value: null
num_bucket_build_workers:
    value: 1
num_reconstruction_vis_samples:
    value: 3
num_workers:
    value: 2
optim:
    value:
        betas:
            - 0.9
            - 0.98
        eps: 1e-08
        lr: 0.0005
        weight_decay: 0
outputs:
    value: outputs
pin_memory_cache_pre_alloc_numels:
    value: null
plugin:
    value: zero2
plugin_config:
    value:
        overlap_allgather: false
        reduce_bucket_size_in_m: 128
prefetch_factor:
    value: 2
seed:
    value: 42
sweep_config:
    value: /home/piado/projects/aip-lindell/piado/vae/Open-Sora/configs/vae/train/wan_multiview_finetune.py
train_target_frames:
    value: 9
train_target_hw:
    value:
        - 128
        - 128
update_warmup_steps:
    value: false
vae_loss_config:
    value:
        kl_loss_weight: 0.0005
        perceptual_loss_weight: 0.5
        view_consistency_weight: 0.01
vae_loss_preset:
    value: default
vae_target_range:
    value: '[-1,1]'
val_dataset:
    value: null
view_flatten_in_disc:
    value: true
view_flatten_in_loss:
    value: false
wandb:
    value: true
wandb_min_steps_before_init:
    value: 10
wandb_project:
    value: wan_multiview_vae
wandb_run_id:
    value: thpqjz2x
wandb_run_url:
    value: https://wandb.ai/pia-uni/wan_multiview_vae/runs/thpqjz2x
