#!/bin/bash
# SLURM array job script for preprocessing NeRSemble data
# Each array task processes one participant/sequence combination
#
# Usage:
#   1. Run discover mode to generate tasks.json
#   2. Replace 230 with actual count: sed "s/%TASK_COUNT%/10/" run_array_job.sh > run_array_job_10.sh
#   3. Submit: sbatch run_array_job_10.sh

#SBATCH --job-name=nersemble_preprocess
#SBATCH --output=logs/preprocess_%A_%a.out  # %A = job ID, %a = array task ID
#SBATCH --error=logs/preprocess_%A_%a.err
#SBATCH --array=1-230%10  # This gets replaced with actual count before submission
# %10 at the end limits to 10 concurrent tasks (adjust as needed based on cluster GPU availability)
#SBATCH --gres=gpu:1  # Need GPU for RobustVideoMatting background removal
#SBATCH --cpus-per-task=4  # For data loading/processing
#SBATCH --mem=32G  # Enough for video processing
#SBATCH --time=02:00:00  # 2 hours should be enough per participant

set -e  # Exit immediately if any command fails

# ============================================================================
# Configuration - adjust these paths for your environment
# ============================================================================
PROJECT_ROOT="/home/piado/projects/aip-lindell/piado"
SCRIPT_DIR="${PROJECT_ROOT}/data/processing"
VENV_PATH="/project/6101839/piado/snth"  # Your virtual environment
NERSEMBLE_ROOT="/scratch/piado/data/nersemble"  # NeRSemble dataset location
OUTPUT_ROOT="${PROJECT_ROOT}/data/preprocessed_initial_experiments"  # Where to save results
TASK_FILE="${SCRIPT_DIR}/tasks.json"  # Generated by discover mode
MATTING_CHECKPOINT="${PROJECT_ROOT}/data/rvm_mobilenetv3.pth"  # Background removal model

# ============================================================================
# Setup
# ============================================================================
# Activate virtual environment (adjust path if needed)
source "${VENV_PATH}/bin/activate"

# Create output directory for logs (SLURM will create log files here)
mkdir -p "${OUTPUT_ROOT}/logs"

# ============================================================================
# Get task index and output dir (0-based index for --task-index)
# ============================================================================
# SLURM_ARRAY_TASK_ID is 1-based; script expects 0-based --task-index
TASK_INDEX=$((${SLURM_ARRAY_TASK_ID} - 1))

# Read participant_id and sequence_name from tasks.json for this index (for OUTPUT_DIR only)
PARTICIPANT_ID=$(python3 -c "
import json
with open('${TASK_FILE}') as f:
    tasks = json.load(f)
idx = ${TASK_INDEX}
if idx < len(tasks):
    print(tasks[idx]['participant_id'])
else:
    exit(1)
")
SEQUENCE_NAME=$(python3 -c "
import json
with open('${TASK_FILE}') as f:
    tasks = json.load(f)
idx = ${TASK_INDEX}
if idx < len(tasks):
    print(tasks[idx]['sequence_name'])
else:
    exit(1)
")
OUTPUT_DIR="${OUTPUT_ROOT}/p${PARTICIPANT_ID}_${SEQUENCE_NAME}"

echo "=========================================="
echo "Array Task: ${SLURM_ARRAY_TASK_ID}"
echo "Participant: ${PARTICIPANT_ID}"
echo "Sequence: ${SEQUENCE_NAME}"
echo "Output: ${OUTPUT_DIR}"
echo "=========================================="

# ============================================================================
# Build and run preprocessing command
# ============================================================================
# Use --task-index and --task-file so we never pass JSON on the command line (avoids shell quoting issues)
CMD="python3 ${SCRIPT_DIR}/preprocess_nersemble.py process"
CMD="${CMD} --task-index ${TASK_INDEX}"
CMD="${CMD} --task-file ${TASK_FILE}"
CMD="${CMD} --nersemble-root ${NERSEMBLE_ROOT}"
CMD="${CMD} --output-dir ${OUTPUT_DIR}"
CMD="${CMD} --device cuda"  # Use GPU for background removal

# Add background removal if checkpoint exists
# If checkpoint doesn't exist, we'll skip background removal (still works, just slower)
if [ -f "${MATTING_CHECKPOINT}" ]; then
    CMD="${CMD} --matting-checkpoint ${MATTING_CHECKPOINT} --matting-variant mobilenetv3"
    echo "Using background removal model: ${MATTING_CHECKPOINT}"
else
    echo "Warning: Background removal checkpoint not found, skipping background removal"
fi

# Run the preprocessing
echo "Running: ${CMD}"
${CMD}

# ============================================================================
# Done
# ============================================================================
echo "Completed task ${SLURM_ARRAY_TASK_ID}"
